### PR TITLE
bunch of new functions

### PR DESCRIPTION
**Pull request by MarconiS**
added functions to download tiles, clip plots, etc. 
Still to be tested though: merge at your own risk :D

### CODE REVIEW

**Review by vscholl — CHANGES_REQUESTED** [review]
Great additions! 

Can you send example code that you use to run the following functions that will help me test them and make sure I am specifying input parameters correctly: 
- **clip_plot** - Clips the AOP tiles to smaller regions with plots containing vst data. 
- **crop_data_to_plot** - What distinguishes this from the previous function? 
- **extract_raster_from_h5**

**Comment by vscholl** [comment]
Hey, I tested, edited, and commented on many of the new functions you added.
See above for requested changes before I can accept the merge request! 

Also, here are my notes for the changes that may help with setting up tests in the near future: 

**get_lat_long**
- Output for this function is the mappingandtagging df with "latitude" and "longitude" columns,
can be substituted back into the vst dataframe by setting vst:mappingandtagging <- get_lat_long(field_data = vst$vst_mappingandtagging).

**from_inventory_to_shp**
- Input dataframe is also the mappingandtagging table, right? So we can call this function in a test like this: from_inventory_to_shp(stem_locations = vst$vst_mappingandtagging) 

**aop_retriever**
- Renamed to be retrieve_aop_data (following the same format as our retrieve_vst_data function, verb-noun is helpful!) 
- The geolocated stem data with lat lon has a field called api.utmZone. Do we want to rename this to be utmZone somewhere? if so, does it make sense to do this within the calc_tree_geolocations.R file? 
- Changes input parameter "years" to be "year", since the neonUtilies::byTileAOP function shows this as a single year to download AOP data for. 
- Can call this function in a test like this: aop_retriever(data = vst_with_lat_lon, year = 2017, products = "DP3.30015.001"). We should probably filter the VST data down to fewer points a for test. 
- Got an error, "[1] "site NIWO could not be fully downloaded! Error in retrieving: DP1.30003.001 for year 2017 . error returned: Error in neonUtilities::byTileAOP(prd, site = tiles[ii, \"siteID\"], year = year, : DP1.30003.001 is not a Level 3 data product ID.\nThis function will only work correctly on mosaicked Level 3 data.\n" -----> It appears that the point cloud is downloaded by flight line? I did a quick search for point cloud data by tile and don't see it...... for now I commented out this data product.
- Added description for the data products that are downloaded by default 
- Removed duplicate DP3.30025.001 in data products parameter

**Comment by vscholl** [comment]
And/or another option is to just merge the file I have tested so far (and then I can work on the testthat scripts) and give you more time to work on the other ones. Let me know what you prefer! I'm excited that this is all coming together :)

**Comment by MarconiS** [comment]
oooki! saw it now: I will make a notebook with examples of the functions, but basically those are all functions called in crop_data_to_plot. One is the python script to clip h5, the other is the function called to clip laz|tif|h5 files.

One problem that will need to be solved is to automatically look for the right python environment. Right now I am assuming that folks have a python Conda environment, but it would be nice to see if we can include a miniconda environment within the build, and directly point to that.

**Comment by MarconiS** [comment]
Ok I have merged on my fork yours edits. As to the point cloud, that is a function that works only in the dev release of the neonUtilities. It won't work (yet) if you use the cran release. Ok with commenting it at the moment

**Comment by MarconiS** [comment]
I'll go ahead and merge the pull request. Am going to add the rm-notebook tomorrow, hopefully :)
 crooooooss fingers am not breaking anything!

**Comment by vscholl** [comment]
I pulled the most recent version and ran devtools::test().
1 is OK and 1 failed, test_calc_tree_geolocations.R. 
Committed a few changes so this test is now OK, so make sure u pull the most recent!

**Comment by vscholl** [comment]
Created a testthat script for get_lat_long

**Pull request merged**
